version: "3.9"

services:
  web:
    build: .
    container_name: bookstore_web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: production
      DATABASE_URI: mysql+pymysql://bookstore_user:bookstore_pass@db/bookstore?charset=utf8mb4
      SECRET_KEY: daylabimatcuaban123456
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: bookstore_db
    restart: always
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: bookstore_pass
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # cho phép bạn kết nối từ bên ngoài (VD: DBeaver)

volumes:
  mysql_data:
